{ Parsed from CoreLocation.framework CLLocationManager+CLVisitExtensions.h }
{$ifdef CLASSES}

type
  CLVisitExtensions = objccategory external (CLLocationManager)
    procedure startMonitoringVisits                       __TVOS_PROHIBITED __WATCHOS_PROHIBITED; message 'startMonitoringVisits                       __TVOS_PROHIBITED __WATCHOS_PROHIBITED'; { available in NA, 8_0 }
    procedure stopMonitoringVisits                       __TVOS_PROHIBITED __WATCHOS_PROHIBITED; message 'stopMonitoringVisits                       __TVOS_PROHIBITED __WATCHOS_PROHIBITED'; { available in NA, 8_0 }
  end;
{$endif}

