{ Parsed from Foundation.framework NSURLError.h }

{$ifdef EXTERNAL_SYMBOLS}
var
  NSURLErrorDomain: NSErrorDomain; cvar; external;
  NSURLErrorFailingURLErrorKey: NSString { available in 10_6, 4_0 }; cvar; external;
  NSURLErrorFailingURLStringErrorKey: NSString { available in 10_6, 4_0 }; cvar; external;
  NSErrorFailingURLStringKey: NSString deprecated 'in 10_0, 10_6, 2_0, 4_0'; cvar; external;
  NSURLErrorFailingURLPeerTrustErrorKey: NSString { available in 10_6, 4_0 }; cvar; external;
  NSURLErrorBackgroundTaskCancelledReasonKey: NSString { available in 10_10, 8_0 }; cvar; external;
{$endif}

