{ Parsed from HomeKit.framework HMAccessoryCategoryTypes.h }
{$ifdef EXTERNAL_SYMBOLS}
var
  HMAccessoryCategoryTypeOther: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeSecuritySystem: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeBridge: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeDoor: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeDoorLock: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeFan: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeGarageDoorOpener: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeIPCamera: NSString { available in 10_0 }; cvar; external;
  HMAccessoryCategoryTypeLightbulb: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeOutlet: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeProgrammableSwitch: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeRangeExtender: NSString { available in 9_3 }; cvar; external;
  HMAccessoryCategoryTypeSensor: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeSwitch: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeThermostat: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeVideoDoorbell: NSString { available in 10_0 }; cvar; external;
  HMAccessoryCategoryTypeWindow: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeWindowCovering: NSString { available in 9_0 }; cvar; external;
  HMAccessoryCategoryTypeAirPurifier: NSString { available in 10_2 }; cvar; external;
  HMAccessoryCategoryTypeAirHeater: NSString { available in 10_2 }; cvar; external;
  HMAccessoryCategoryTypeAirConditioner: NSString { available in 10_2 }; cvar; external;
  HMAccessoryCategoryTypeAirHumidifier: NSString { available in 10_2 }; cvar; external;
  HMAccessoryCategoryTypeAirDehumidifier: NSString { available in 10_2 }; cvar; external;
{$endif}

