{ Parsed from HomeKit.framework HMServiceTypes.h }
{$ifdef EXTERNAL_SYMBOLS}
var
  HMServiceTypeLightbulb: NSString { available in 8_0 }; cvar; external;
  HMServiceTypeSwitch: NSString { available in 8_0 }; cvar; external;
  HMServiceTypeThermostat: NSString { available in 8_0 }; cvar; external;
  HMServiceTypeGarageDoorOpener: NSString { available in 8_0 }; cvar; external;
  HMServiceTypeAccessoryInformation: NSString { available in 8_0 }; cvar; external;
  HMServiceTypeFan: NSString { available in 8_0 }; cvar; external;
  HMServiceTypeOutlet: NSString { available in 8_0 }; cvar; external;
  HMServiceTypeLockMechanism: NSString { available in 8_0 }; cvar; external;
  HMServiceTypeLockManagement: NSString { available in 8_0 }; cvar; external;
  HMServiceTypeAirQualitySensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeBattery: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeCarbonDioxideSensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeCarbonMonoxideSensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeContactSensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeDoor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeDoorbell: NSString { available in 10_0 }; cvar; external;
  HMServiceTypeHumiditySensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeLeakSensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeLightSensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeMotionSensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeOccupancySensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeSecuritySystem: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeStatefulProgrammableSwitch: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeStatelessProgrammableSwitch: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeSmokeSensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeTemperatureSensor: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeWindow: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeWindowCovering: NSString { available in 9_0 }; cvar; external;
  HMServiceTypeCameraRTPStreamManagement: NSString { available in 10_0 }; cvar; external;
  HMServiceTypeCameraControl: NSString { available in 10_0 }; cvar; external;
  HMServiceTypeMicrophone: NSString { available in 10_0 }; cvar; external;
  HMServiceTypeSpeaker: NSString { available in 10_0 }; cvar; external;
  HMServiceTypeAirPurifier: NSString { available in 10_2 }; cvar; external;
  HMServiceTypeVentilationFan: NSString { available in 10_2 }; cvar; external;
  HMServiceTypeFilterMaintenance: NSString { available in 10_2 }; cvar; external;
  HMServiceTypeHeaterCooler: NSString { available in 10_2 }; cvar; external;
  HMServiceTypeHumidifierDehumidifier: NSString { available in 10_2 }; cvar; external;
  HMServiceTypeSlats: NSString { available in 10_2 }; cvar; external;
{$endif}

