{ Parsed from Security.framework SecImportExport.h }

{$ifndef _SECURITY_SECIMPORTEXPORT_H_}
{$ifdef EXTERNAL_SYMBOLS}
var
  kSecImportExportPassphrase: CFStringRef { available starting in __MAC_10_6, __IPHONE_2_0 }; cvar; external;
  kSecImportItemLabel: CFStringRef { available starting in __MAC_10_6, __IPHONE_2_0 }; cvar; external;
  kSecImportItemKeyID: CFStringRef { available starting in __MAC_10_6, __IPHONE_2_0 }; cvar; external;
  kSecImportItemTrust: CFStringRef { available starting in __MAC_10_6, __IPHONE_2_0 }; cvar; external;
  kSecImportItemCertChain: CFStringRef { available starting in __MAC_10_6, __IPHONE_2_0 }; cvar; external;
  kSecImportItemIdentity: CFStringRef { available starting in __MAC_10_6, __IPHONE_2_0 }; cvar; external;
{$endif}

{$endif}
