{ Parsed from UIKit.framework UIContentSizeCategory.h }
{$ifdef TYPES}
type
  NS_STRING_ENUM = NSString *UIContentSizeCategory { available in 7_0 };
  NS_STRING_ENUMPtr = ^NS_STRING_ENUM { available in 7_0 };
{$endif}

{$ifdef EXTERNAL_SYMBOLS}
var
  UIContentSizeCategoryUnspecified: UIContentSizeCategory { available in 10_0 }; cvar; external;
  UIContentSizeCategoryExtraSmall: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategorySmall: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryMedium: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryLarge: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryExtraLarge: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryExtraExtraLarge: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryExtraExtraExtraLarge: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryAccessibilityMedium: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryAccessibilityLarge: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryAccessibilityExtraLarge: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryAccessibilityExtraExtraLarge: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryAccessibilityExtraExtraExtraLarge: UIContentSizeCategory { available in 7_0 }; cvar; external;
  UIContentSizeCategoryDidChangeNotification: NSNotificationName { available in 7_0 }; cvar; external;
  UIContentSizeCategoryNewValueKey: NSString { available in 7_0 }; cvar; external;
{$endif}

