{ Parsed from Intents.framework INCarSeat.h }

{$ifndef INCarSeat_h}
{$ifdef TYPES}
type
  INCarSeat = NSInteger;
  INCarSeatPtr = ^INCarSeat;

const
  INCarSeatUnknown = 0;
  INCarSeatDriver = 1;
  INCarSeatPassenger = 2;
  INCarSeatFrontLeft = 3;
  INCarSeatFrontRight = 4;
  INCarSeatFront = 5;
  INCarSeatRearLeft = 6;
  INCarSeatRearRight = 7;
  INCarSeatRear = 8;
  INCarSeatThirdRowLeft = 9;
  INCarSeatThirdRowRight = 10;
  INCarSeatThirdRow = 11;
{$endif}

{$endif}
