{ Parsed from Intents.framework INCarAudioSource.h }

{$ifndef INCarAudioSource_h}
{$ifdef TYPES}
type
  INCarAudioSource = NSInteger;
  INCarAudioSourcePtr = ^INCarAudioSource;

const
  INCarAudioSourceUnknown = 0;
  INCarAudioSourceCarPlay = 1;
  INCarAudioSourceiPod = 2;
  INCarAudioSourceRadio = 3;
  INCarAudioSourceBluetooth = 4;
  INCarAudioSourceAUX = 5;
  INCarAudioSourceUSB = 6;
  INCarAudioSourceMemoryCard = 7;
  INCarAudioSourceOpticalDrive = 8;
  INCarAudioSourceHardDrive = 9;
{$endif}

{$endif}
