{ Parsed from Intents.framework INIntentIdentifiers.h }
{$ifdef FUNCTIONS}
function API_UNAVAILABLE_____(param1: macosx): NSString * INSetAudioSourceInCarIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE______(param1: macosx): NSString * INSetClimateSettingsInCarIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE_______(param1: macosx): NSString * INSetDefrosterSettingsInCarIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE________(param1: macosx): NSString * INSetSeatSettingsInCarIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE_________(param1: macosx): NSString * INSetProfileInCarIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE__________(param1: macosx): NSString * INSaveProfileInCarIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE___________(param1: macosx): NSString * INStartWorkoutIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE____________(param1: macosx): NSString * INPauseWorkoutIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE_____________(param1: macosx): NSString * INEndWorkoutIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE______________(param1: macosx): NSString * INCancelWorkoutIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE_______________(param1: macosx): NSString * INResumeWorkoutIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE________________(param1: macosx): NSString * INSetRadioStationIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE_________________(param1: macosx): NSString * INSendPaymentIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE__________________(param1: macosx): NSString * INRequestPaymentIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE___________________(param1: macosx): NSString * INSearchForPhotosIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE____________________(param1: macosx): NSString * INStartPhotoPlaybackIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE_____________________(param1: macosx): NSString * INListRideOptionsIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE______________________(param1: macosx): NSString * INRequestRideIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
function API_UNAVAILABLE_______________________(param1: macosx): NSString * INGetRideStatusIntentIdentifier                        ); cdecl; external; { available in ios(10.0 }
{$endif}

