{ Parsed from Intents.framework INPhotoAttributeOptions.h }

{$ifndef INPhotoAttributeOptions_h}
{$ifdef TYPES}
type
  INPhotoAttributeOptions = NSUInteger;
  INPhotoAttributeOptionsPtr = ^INPhotoAttributeOptions;

const
  INPhotoAttributeOptionPhoto = 1 shl 0;
  INPhotoAttributeOptionVideo = 1 shl 1;
  INPhotoAttributeOptionGIF = 1 shl 2;
  INPhotoAttributeOptionFlash = 1 shl 3;
  INPhotoAttributeOptionLandscapeOrientation = 1 shl 4;
  INPhotoAttributeOptionPortraitOrientation = 1 shl 5;
  INPhotoAttributeOptionFavorite = 1 shl 6;
  INPhotoAttributeOptionSelfie = 1 shl 7;
  INPhotoAttributeOptionFrontFacingCamera = 1 shl 8;
  INPhotoAttributeOptionScreenshot = 1 shl 9;
  INPhotoAttributeOptionBurstPhoto = 1 shl 10;
  INPhotoAttributeOptionHDRPhoto = 1 shl 11;
  INPhotoAttributeOptionSquarePhoto = 1 shl 12;
  INPhotoAttributeOptionPanoramaPhoto = 1 shl 13;
  INPhotoAttributeOptionTimeLapseVideo = 1 shl 14;
  INPhotoAttributeOptionSlowMotionVideo = 1 shl 15;
  INPhotoAttributeOptionNoirFilter = 1 shl 16;
  INPhotoAttributeOptionChromeFilter = 1 shl 17;
  INPhotoAttributeOptionInstantFilter = 1 shl 18;
  INPhotoAttributeOptionTonalFilter = 1 shl 19;
  INPhotoAttributeOptionTransferFilter = 1 shl 20;
  INPhotoAttributeOptionMonoFilter = 1 shl 21;
  INPhotoAttributeOptionFadeFilter = 1 shl 22;
  INPhotoAttributeOptionProcessFilter = 1 shl 23;
{$endif}

{$endif}
