{ Parsed from Intents.framework INSiriAuthorizationStatus.h }

{$ifndef INSiriAuthorizationStatus_h}
{$ifdef TYPES}
type
  INSiriAuthorizationStatus = NSInteger;
  INSiriAuthorizationStatusPtr = ^INSiriAuthorizationStatus;

const
  INSiriAuthorizationStatusNotDetermined = 0;
  INSiriAuthorizationStatusRestricted = 1;
  INSiriAuthorizationStatusDenied = 2;
  INSiriAuthorizationStatusAuthorized = 3;
{$endif}

{$endif}
