{ Parsed from Intents.framework INWorkoutNameIdentifier.h }
{$ifdef TYPES}
type
  NS_STRING_ENUM = NSString *INWorkoutNameIdentifier;
  NS_STRING_ENUMPtr = ^NS_STRING_ENUM;
{$endif}

{$ifdef FUNCTIONS}
function API_UNAVAILABLE________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierRun NS_SWIFT_NAME(INWorkoutNameIdentifier.run)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE_________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierSit NS_SWIFT_NAME(INWorkoutNameIdentifier.sit)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE__________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierSteps NS_SWIFT_NAME(INWorkoutNameIdentifier.steps)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE___________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierStand NS_SWIFT_NAME(INWorkoutNameIdentifier.stand)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE____________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierMove NS_SWIFT_NAME(INWorkoutNameIdentifier.move)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE_____________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierWalk NS_SWIFT_NAME(INWorkoutNameIdentifier.walk)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE______________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierYoga NS_SWIFT_NAME(INWorkoutNameIdentifier.yoga)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE_______________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierDance NS_SWIFT_NAME(INWorkoutNameIdentifier.dance)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierCrosstraining NS_SWIFT_NAME(INWorkoutNameIdentifier.crosstraining)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE_________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierElliptical NS_SWIFT_NAME(INWorkoutNameIdentifier.elliptical)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE__________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierRower NS_SWIFT_NAME(INWorkoutNameIdentifier.rower)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE___________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierCycle NS_SWIFT_NAME(INWorkoutNameIdentifier.cycle)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE____________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierStairs NS_SWIFT_NAME(INWorkoutNameIdentifier.stairs)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE_____________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierOther NS_SWIFT_NAME(INWorkoutNameIdentifier.other)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE______________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierIndoorrun NS_SWIFT_NAME(INWorkoutNameIdentifier.indoorrun)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE_______________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierIndoorcycle NS_SWIFT_NAME(INWorkoutNameIdentifier.indoorcycle)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE________________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierIndoorwalk NS_SWIFT_NAME(INWorkoutNameIdentifier.indoorwalk)                        ); cdecl; external; { available in ios(10.2 }
function API_UNAVAILABLE_________________________________________(param1: macosx): INWorkoutNameIdentifier  INWorkoutNameIdentifierExercise NS_SWIFT_NAME(INWorkoutNameIdentifier.exercise)                        ); cdecl; external; { available in ios(10.2 }
{$endif}

