{ Parsed from Intents.framework INWorkoutGoalUnitType.h }

{$ifndef INWorkoutGoalUnitType_h}
{$ifdef TYPES}
type
  INWorkoutGoalUnitType = NSInteger;
  INWorkoutGoalUnitTypePtr = ^INWorkoutGoalUnitType;

const
  INWorkoutGoalUnitTypeUnknown = 0;
  INWorkoutGoalUnitTypeInch = 1;
  INWorkoutGoalUnitTypeMeter = 2;
  INWorkoutGoalUnitTypeFoot = 3;
  INWorkoutGoalUnitTypeMile = 4;
  INWorkoutGoalUnitTypeYard = 5;
  INWorkoutGoalUnitTypeSecond = 6;
  INWorkoutGoalUnitTypeMinute = 7;
  INWorkoutGoalUnitTypeHour = 8;
  INWorkoutGoalUnitTypeJoule = 9;
  INWorkoutGoalUnitTypeKiloCalorie = 10;
{$endif}

{$endif}
